# Generated by Django 2.0.1 on 2018-01-29 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsitecontent',
            name='is_live',
            field=models.BooleanField(default=False, help_text='Checking this will make this Main Site Content live and all others will be unchecked'),
        ),
    ]
