# Generated by Django 2.0.1 on 2018-01-29 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site_content', '0002_mainsitecontent_is_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
