# Generated by Django 2.0.1 on 2018-01-29 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site_content', '0003_skill_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsitecontent',
            name='apple_touch_icon',
            field=models.ImageField(help_text='Add an icon for Apple Touch. Should be a common filetype and 144x144 px', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mainsitecontent',
            name='favicon',
            field=models.ImageField(help_text='Add a favicon. Should be a common filetype and 16x16 px', null=True, upload_to=''),
        ),
    ]
