# Generated by Django 2.0.1 on 2018-02-02 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site_content', '0004_auto_20180129_0204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainsitecontent',
            options={'verbose_name': 'Main Site Content', 'verbose_name_plural': 'Main Site Content Configurations'},
        ),
    ]
