# Generated by Django 2.0.1 on 2018-01-29 00:48

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Category name. Maximum 50 characters', max_length=50)),
                ('is_live', models.BooleanField(default=False, help_text='Check this when the category is ready to go live')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('portfolio_header', models.CharField(blank=True, help_text='A header for carousels of photos within this category', max_length=100)),
                ('portfolio_body', models.TextField(blank=True, help_text='Body for carousels of photos within this category. Can be multi-paragraph')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('-is_live', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('is_live', models.BooleanField(default=False, help_text='Check this when the image is ready to go live')),
                ('title', models.CharField(blank=True, help_text='Max 200 characters', max_length=200)),
                ('heading', models.CharField(blank=True, help_text='First heading. Max 1000 characters.', max_length=1000)),
                ('subheading', models.CharField(blank=True, help_text='Second heading. Max 1000 characters.', max_length=1000)),
                ('customers_can_buy_prints', models.BooleanField(default=False, help_text='Check this when prints are available for purchase')),
                ('category', models.ForeignKey(blank=True, help_text='Choose a category or leave blank', null=True, on_delete=django.db.models.deletion.SET_NULL, to='photos.Category')),
            ],
        ),
        migrations.CreateModel(
            name='UUIDTaggedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.UUIDField(db_index=True, verbose_name='Object id')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_uuidtaggeditem_tagged_items', to='contenttypes.ContentType', verbose_name='Content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_uuidtaggeditem_items', to='taggit.Tag')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='photos.UUIDTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
