# Generated by Django 2.0.1 on 2018-02-02 04:58

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Separate by commas. "Use quotes" for multi-word tags', through='photos.UUIDTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
