# Generated by Django 2.0.1 on 2018-02-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='attribution',
            field=models.CharField(default='', help_text='Similar to a byline, follows the clickable text', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='link_text',
            field=models.CharField(blank=True, help_text='Clickable text', max_length=200),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='link',
            field=models.URLField(help_text='Enter the link URL'),
        ),
    ]
