# Generated by Django 2.0.1 on 2018-02-02 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_galleryimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='background_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='background_image', to='photos.Photo'),
        ),
    ]
